name: Generate Metrics
on:
  schedule: [{cron: "0 * * * *"}] # Runs every hour
  workflow_dispatch: # Allows manual runs
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Jai-Dhiman
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage
          plugin_stars: yes
          plugin_stars_limit: 2
          plugin_activity: yes
